// svelte/src/routes/document-scanner/+page.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import ScanbotSDKService from '../../service/scanbot-sdk-service';
	import Header from '../../subviews/Header.svelte';
	onMount(async () => {
		ScanbotSDKService.instance.createDocumentScanner('document-scanner');
	});
	onDestroy(() => {
		ScanbotSDKService.instance.disposeDocumentScanner();
	});
</script>

<Header title="Document Scanner" isBackButtonVisible={true} />

<div id="document-scanner" style="width: 100%; height: calc(100vh - 50px); background-color: black" />

// next-js/src/app/pages/document-scanner/page.tsx
"use client";

import { useEffect } from "react";
import Header from "../../subviews/header";
import ScanbotSDKService from "../../services/scanbot-sdk-service";

export default function DocumentScanner() {
    
    useEffect(() => {
        ScanbotSDKService.instance.createDocumentScanner("document-scanner");

        return () => {
            ScanbotSDKService.instance.disposeDocumentScanner();
        };
    }, [])

    return (
        <div>
            <Header backPath={"/"} />
            <div id="document-scanner" style={{ width: "100%", height: "calc(100vh - 60px)" }} />
        </div>
    )
}
