// angular-js/src/app/app.component.ts
import {Component} from "@angular/core";

// Import SDK from webpack directory to ensure web assembly binary and worker and bundled with webpack
import ScanbotSDK from "scanbot-web-sdk/webpack";

// Other typings should be imported from @types
import {InitializationOptions} from "scanbot-web-sdk/@types/model/configuration/initialization-options";
import {DocumentScannerConfiguration} from "scanbot-web-sdk/@types/model/configuration/document-scanner-configuration";
import {DetectionResult} from "scanbot-web-sdk/@types/model/response/detection-result";
import {IDocumentScannerHandle} from "scanbot-web-sdk/@types/interfaces/i-document-scanner-handle";
import {ICroppingViewHandle} from "scanbot-web-sdk/@types/interfaces/i-cropping-view-handle";
import {CroppingViewConfiguration} from "scanbot-web-sdk/@types/model/configuration/cropping-view-configuration";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  features: any = [
    { name: "Scan Documents", action: () => {}},
    { name: "Pick image", action: () => {}},
    { name: "Image Results", action: () => {}},
    { name: "Check License", action: () => {}}
  ];

  SCANNER_CONTAINER = "scanbot-camera-container";

  license = "";
  SDK: ScanbotSDK | undefined;

  documentScanner?: IDocumentScannerHandle;
  croppingView?: ICroppingViewHandle;

  async ngOnInit() {
    const options: InitializationOptions = {
      // License key is a required parameter, leave empty for trial
      licenseKey: ""
      // Optional: configure another source for the engine
      // engine: "lib/"
    };

    // this.SDK = await ScanbotSDK.initialize(options);

    // const configuration: DocumentScannerConfiguration = {
    //   onDocumentDetected: this.onDocumentDetected.bind(this),
    //   containerId: this.SCANNER_CONTAINER
    // };
    //
    // await this.SDK.createDocumentScanner(configuration);
  }

  async onDocumentDetected(result: DetectionResult) {
    console.log("Detected document: ", result);
    const image = result.cropped ?? result.original;
    this.documentScanner?.dispose();
    const config: CroppingViewConfiguration = {
      image: image,
      polygon: result.polygon,
      containerId: this.SCANNER_CONTAINER
    };
    this.croppingView = await this.SDK?.openCroppingView(config);
  }
}


<!-- Toolbar -->
<div class="toolbar" role="banner">
  <img width="40" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="/>
  <span>Scanbot Web SDK Example</span>
  <div class="spacer"></div>
</div>

<div class="content" role="main">

  <svg id="clouds" alt="Gray Clouds Background" xmlns="http://www.w3.org/2000/svg"
       width="2611.084" height="485.677" viewBox="0 0 2611.084 485.677">
    <path id="Path_39" data-name="Path 39" d="M2379.709,863.793c10-93-77-171-168-149-52-114-225-105-264,
    15-75,3-140,59-152,133-30,2.83-66.725,9.829-93.5,
    26.25-26.771-16.421-63.5-23.42-93.5-26.25-12-74-77-130-152-133-39-120-212-129-264-15-54.084-13.075-106.753,
    9.173-138.488,48.9-31.734-39.726-84.4-61.974-138.487-48.9-52-114-225-105-264,15a162.027,162.027,0,0,0-103.147,
    43.044c-30.633-45.365-87.1-72.091-145.206-58.044-52-114-225-105-264,15-75,3-140,59-152,133-53,5-127,23-130,
    83-2,42,35,72,70,86,49,20,106,18,157,5a165.625,165.625,0,0,0,120,0c47,94,178,113,251,33,61.112,8.015,113.854-5.72,
    150.492-29.764a165.62,165.62,0,0,0,110.861-3.236c47,94,178,113,251,33,31.385,4.116,60.563,2.495,86.487-3.311,
    25.924,5.806,55.1,7.427,86.488,3.311,73,80,204,61,251-33a165.625,165.625,0,0,0,120,0c51,13,108,15,
    157-5a147.188,147.188,0,0,0,33.5-18.694,147.217,147.217,0,0,0,33.5,18.694c49,20,106,18,157,5a165.625,165.625,
    0,0,0,120,0c47,94,178,113,251,33C2446.709,1093.793,2554.709,922.793,2379.709,863.793Z"
          transform="translate(142.69 -634.312)" fill="#eee"/>
  </svg>

  <router-outlet></router-outlet>
</div>

// react-js/src/App.tsx
import React from 'react';
import './App.css';
import {AppBar, Toolbar, Typography} from "@material-ui/core";
import Lightbox from 'react-image-lightbox';
import 'react-image-lightbox/style.css'; // This only needs to be imported once in your app

// Import SDK from webpack directory to ensure web assembly binary and worker and bundled with webpack
import ScanbotSDK from "scanbot-web-sdk/webpack";

// Other typings should be imported from the component folder
import {DocumentScannerConfiguration} from "scanbot-web-sdk/component/model/configuration/document-scanner-configuration";
import DocumentScannerView from "scanbot-web-sdk/component/document-scanner-view";
import {DetectionResult} from "scanbot-web-sdk/component/model/response/detection-result";
import {CroppingViewConfiguration} from "scanbot-web-sdk/component/model/configuration/cropping-view-configuration";
import CroppingView from "scanbot-web-sdk/component/cropping-view";

export default class App extends React.Component<any, any> {

    SCANNER_CONTAINER = "document-scanner-view";
    license = "";
    SDK: ScanbotSDK | undefined;

    document: any;

    constructor(props: any) {
        super(props);
        this.state = {
            image: undefined,
            configuration: {
                scanner: undefined,
                cropping: undefined
            }
        };
    }

    async componentDidMount() {
        this.SDK = await ScanbotSDK.initialize({licenseKey: this.license, engine: "/"});

        if (!this.SDK.initialized) {
            const info = await this.SDK.getLicenseInfo();
            console.log("Something went wrong. Here's your license info:", info);
            return;
        }

        const configuration: DocumentScannerConfiguration = {
            onDocumentDetected: async (result: DetectionResult) => {
                console.log("Detected document: ", result);
                const image = result.cropped ?? result.original;
                this.setState({
                    image: await this.SDK?.toDataUrl(image),
                    configuration: {
                        ...configuration,
                        cropping: {image: image, polygon: result.polygon}
                    }
                });
            },
            containerId: this.SCANNER_CONTAINER
        };

        await this.SDK.createDocumentScanner(configuration);
        // this.setState({configuration: {document: document}});
    }

    render() {
        return (
            <div>
                <AppBar position="fixed">
                    <Toolbar><Typography variant="h6">Scanbot Web SDK Example</Typography></Toolbar>
                </AppBar>
                <div style={{height: "100vh"}}>
                    {/*{this.state.configuration.document && <DocumentScannerView configuration={this.state.configuration.document}/>}*/}
                    <div id={this.SCANNER_CONTAINER} style={{width: "100%", height: "100%"}}/>
                </div>
                {this.state.image && <Lightbox mainSrc={this.state.image} onCloseRequest={this.closePopup.bind(this)}/>}
                {/*<div style={{height: "100vh"}}>*/}
                {/*    {this.state.image && <CroppingView configuration={this.state.configuration.cropping}/>}*/}
                {/*</div>*/}
            </div>
        );
    }

    closePopup() {
        this.setState({image: undefined});
    }
}
