// svelte/src/routes/image-results/+page.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import ScanbotSDKService from '../../service/scanbot-sdk-service';
    import Header from '../../subviews/Header.svelte';
    import type { SBStoreDocumentScannerResponse } from "scanbot-web-sdk/@types";

    let images: { base64: string, document: SBStoreDocumentScannerResponse }[] = [];

    onMount(async () => {
        await ScanbotSDKService.instance.initialize();
        const documents = await ScanbotSDKService.instance.getDocuments();
        console.log('Total documents:', documents.length);

        images = await Promise.all(documents.map(async (doc) => {
			const base64 = await ScanbotSDKService.instance.toDataUrl(doc);
			return { base64, document: doc };
		}));
    });
</script>

<Header title="Image Results" isBackButtonVisible={true} />

{#if images.length === 0}
    <div style="display: flex; justify-content: center; padding-top: 20%">
        <div>Your scanned documents will be displayed here</div>
    </div>
{/if}

<div class="document-gallery">
    {#each images as image}
        <div class="image-container">
            <a href="image-results/image-details?id={image.document.id}">
                <img class="document-image" src={image.base64} alt="<document>" />
            </a>
        </div>
    {/each}
</div>

<style>
    .document-gallery {
        margin-top: 10%;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 10px;
    }

    .image-container {
        flex-basis: 30%;
    }

    .document-image {
        height: auto;
        object-fit: contain;
        border-radius: 5px;
        max-width: 100%;
        vertical-align: middle;
    }
</style>

// angular-js-new/src/app/image-results/image-results.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { ScanbotService } from '../../service/scanbot.service';
import ScanbotSDK from 'scanbot-web-sdk';
import { Image } from 'scanbot-web-sdk/@types';

@Component({
  selector: 'app-image-results',
  templateUrl: './image-results.component.html',
})
export class ImageResultsComponent implements OnInit {

  private scanbot = inject(ScanbotService);

  IMAGES: string[] = [];

  async ngOnInit() {
    const sdk = await this.scanbot.getSdk();
    const results = await sdk.storage.getCroppedDetectionResults(false);
    console.log("Cropped detection results:", results);

    results.forEach((item) => {
      sdk.storage.getCroppedDetectionResultImage(item.id).then(async (images) => {
        if (images && images.length > 0) {
          const original = images.find(i => i.documentId === item.id && i.type === "original");
          const cropped = images.find(i => i.documentId === item.id && i.type === "cropped");

          let image: Image;
          if (cropped) {
            image = ScanbotSDK.Config.Image.fromWrappedImage(cropped.data);
          } else {
            image = ScanbotSDK.Config.Image.fromWrappedImage(original!.data);
          }
          const jpeg = await image.toJpeg();
          const base64 = await this.toDataUrl(jpeg);
          this.IMAGES.push(base64);
        } else {
          console.warn("No images found for item:", item.id);
        }
      });
    });
  }

  toDataUrl(buffer: ArrayBuffer): Promise<string> {
    return new Promise((resolve, reject) => {
      const blob = new Blob([buffer], { type: 'image/jpeg' });
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });
  }
}


<style>

  .image-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    margin: 10px;
  }

  .result-image {
    margin: 5px;
    border: 1px solid #ccc;
    background-color: rgba(200, 200, 200, 0.5);
    border-radius: 4px;
    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.1);
    transition: transform 0.2s;
    object-fit: contain;
    width: 100px;
    height: 100px;
  }

</style>
<div class="image-container">
  @for (image of images; track image) {
    <img class="result-image" [src]=image.base64 [attr.alt]="" [attr.title]="" (click)="onImageClick(image)" />
  }
</div>
