// svelte/src/routes/barcode-scanner/+page.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import ScanbotSDKService from '../../service/scanbot-sdk-service';
	import Header from '../../subviews/Header.svelte';
	onMount(async () => {
		ScanbotSDKService.instance.createBarcodeScanner('barcode-scanner');
	});
	onDestroy(() => {
		ScanbotSDKService.instance.disposeBarcodeScanner();
	});
</script>

<Header title="Barcode Scanner" isBackButtonVisible={true} />

<div id="barcode-scanner" style="width: 100%; height: calc(100vh - 50px)" />

// next-js/src/app/barcode-scanner/page.tsx
"use client";

import { useEffect } from "react";
import Header from "../subviews/header";
import ScanbotSDKService from "../services/scanbot-sdk-service";

export default function BarcodeScanner() {

    useEffect(() => {
        ScanbotSDKService.instance.createBarcodeScanner("barcode-scanner");

        return () => {
            ScanbotSDKService.instance.disposeBarcodeScanner();
        };
    }, [])

    return (
        <div>
            <Header backPath={"/"} />
            <div id="barcode-scanner" style={{ width: "100%", height: "calc(100vh - 50px)" }} />
        </div>
    )
}
