// next-js/src/app/pages/barcode-scanner/page.tsx
"use client";

import { useEffect } from "react";
import Header from "../../subviews/header";
import ScanbotSDKService from "../../services/scanbot-sdk-service";
import Image from 'next/image';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function BarcodeScanner() {

    useEffect(() => {
        ScanbotSDKService.instance.createBarcodeScanner("barcode-scanner", async (barcode) => {
            const base64Image = await ScanbotSDKService.instance.sdk?.toDataUrl(barcode.barcodeImage);
            toast(`Detected code: ${barcode.text} (${barcode.format})`, {
                icon: ({theme, type}) =>  <Image width={25} height={25} src={base64Image!} alt="X"/>
              });
        });

        return () => {
            // To avoid memory leaks, always dispose the scanner when the component is unmounted
            ScanbotSDKService.instance.disposeBarcodeScanner();
        };
    }, [])

    return (
        <div>
            <Header backPath={"/"} />
            <div id="barcode-scanner" style={{ width: "100%", height: "calc(100vh - 50px)" }} />
            <ToastContainer autoClose={2000} />
        </div>
    )
}

// svelte/src/routes/barcode-scanner/+page.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import ScanbotSDKService from '../../service/scanbot-sdk-service';
	import Header from '../../subviews/Header.svelte';
	onMount(async () => {
		ScanbotSDKService.instance.createBarcodeScanner('barcode-scanner');
	});
	onDestroy(() => {
		ScanbotSDKService.instance.disposeBarcodeScanner();
	});
</script>

<Header title="Barcode Scanner" isBackButtonVisible={true} />

<div id="barcode-scanner" style="width: 100%; height: calc(100vh - 50px)" />
