// svelte/src/routes/image-details/cropping/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import ScanbotSDKService from '../../../service/scanbot-sdk-service';
	import Apply from '../../../subviews/toast/icon/Apply.svelte';
	import Cancel from '../../../subviews/toast/icon/Cancel.svelte';
	import Header from '../../../subviews/Header.svelte';
	import { onMount } from 'svelte';

	const id = $page.url.searchParams.get('id');
	const document = ScanbotSDKService.instance.getDocument(id);
    
    onMount(async () => {
        await ScanbotSDKService.instance.openCroppingView("cropping-view", id);
    });
</script>

<Header title="Image Details" isBackButtonVisible={true} />

<div class="image-container">
	<div id="cropping-view" />
</div>

<div class="action-item-container">
	<button
		class="no-style crop-button"
		on:click={() => {
			console.log('asdf');
		}}><Cancel /></button
	>
	<button
		class="no-style crop-button"
		on:click={() => {
			console.log('asdf');
		}}><Apply /></button
	>
</div>

<style>
	.image-container {
		display: flex;
		padding: 10px;
	}
	#cropping-view {
		width: 100%;
		height: calc(100vh - 200px);
		border-radius: 5px;
	}
	.action-item-container {
		display: flex;
		justify-content: space-between;
		position: fixed;
		bottom: 0;
		width: 94%;
		margin: 3%;
	}
	.crop-button {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 60px;
		height: 60px;
		border-radius: 50%;
		border: none;
		outline: none;
		cursor: pointer;
		background-color: #c8193c;
		box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
	}
</style>

// next-js/src/app/pages/cropping/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from 'next/navigation'
import Image from 'next/image';

import Header from "../../subviews/header";
import ScanbotSDKService, { ScanbotDocument } from "@/app/services/scanbot-sdk-service";
import Link from "next/link";

export default function Cropping() {

    const params = useSearchParams()

    const [document, setDocument] = useState<ScanbotDocument>();

    useEffect(() => {
        console.log("params", params);
        const document = ScanbotSDKService.instance.findDocument(params.get("id") as string);
        setDocument(document!);
        async function open() { await ScanbotSDKService.instance.openCroppingView('cropping-view', document?.id) };
        open();
    }, [params, document])

    return (
        <div>
            <Header backPath={`/pages/document?id=${document?.id}`} />
            <div style={{
                display: "flex",
                padding: 10,
                backgroundColor: "white",
                height: "calc(100vh - 60px)",
            }}>
                <div id="cropping-view" style={{
                    backgroundColor: "rgb(230, 230, 230)",
                    width: "100%",
                    height: "calc(100vh - 200px)",
                    borderRadius: 5
                }} />
            </div>

        </div>
    )
}
